export const FETCH_PROPERTY = "FETCH_PROPERTY";
export const FETCH_PROPERTY_SUCCESS = "FETCH_PROPERTY:SUCCESS";
export const FETCH_PROPERTY_ERROR = "FETCH_PROPERTY:ERROR";


export const ADD_PROPERTY = "ADD_PROPERTY";
export const ADD_PROPERTY_SUCCESS = "ADD_PROPERTY:SUCCESS";
export const ADD_PROPERTY_ERROR = "ADD_PROPERTY:ERROR";


export const RESERVE_PROPERTY = "RESERVE_PROPERTY";
export const RESERVE_PROPERTY_SUCCESS = "RESERVE_PROPERTY:SUCCESS";
export const RESERVE_PROPERTY_ERROR = "RESERVE_PROPERTY:ERROR";

export const CANCEL_PROPERTY_BOOKING = "CANCEL_PROPERTY_BOOKING";
export const CANCEL_PROPERTY_BOOKING_SUCCESS = "CANCEL_PROPERTY_BOOKING:SUCCESS";
export const CANCEL_PROPERTY_BOOKING_ERROR = "CANCEL_PROPERTY_BOOKING:ERROR";
